spring:
  datasource:
    url: ${data.url}
    username: ${data.username}
    password: ${data.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate.naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      file-size-threshold: 5KB
      max-file-size: 150MB
      max-request-size: 105MB

  data:
    redis:
      port: 6379
      host: localhost

  cache:
    redis:
      time-to-live: 18000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.user}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
